<a href="https://colab.research.google.com/github/KhushiChaudhary-cyber/python_programs/blob/main/matrix_transpose_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
"""
Problem 13: Transpose a 2D matrix
"""

import numpy as np

def get_matrix(rows=4, cols=5):
    """
    Collect matrix input from user
    """
    matrix = []
    print(f"Enter {rows}x{cols} matrix:")

    for i in range(rows):
        while True:
            try:
                row = list(map(int, input(f"Row {i+1}: ").split()))
                if len(row) != cols:
                    print("Enter correct number of elements.")
                    continue
                matrix.append(row)
                break
            except ValueError:
                print("Invalid input.")

    return np.array(matrix)


# Take matrix input
matrix = get_matrix()

# Transpose matrix using NumPy
transpose = matrix.T

# Display result
print("\nTransposed Matrix:\n", transpose)


Enter 4x5 matrix:
Row 1: 1 2 3 4 5
Row 2:  6 7 8 9 10
Row 3: 11 12 13  14 15 
Row 4: 16 17 18 19 20

Transposed Matrix:
 [[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
